# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
list1 = [50, 60, 80, 100, 200, 300, 500, 600, 700]
list1

[50, 60, 80, 100, 200, 300, 500, 600, 700]

In [2]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600, 700])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 4 ,6], [3, 6, 9]])
my_matrix

array([[2, 4, 6],
       [3, 6, 9]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
array = np.array([[3, 7, 9, 3], [4, 3, 2, 2]])
array

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.18938066, 0.3992754 , 0.71258916, 0.90560828, 0.62277299,
       0.62049841, 0.64400768, 0.76130061, 0.52522145, 0.69188452,
       0.70643171, 0.20966987, 0.33045737, 0.92098514, 0.46262392,
       0.97371312, 0.61497507, 0.54307896, 0.4773236 , 0.88631664])

In [7]:
# you can create a matrix of random number as well
y = np.random.rand(3,3)
y

array([[0.4186099 , 0.65443016, 0.84581014],
       [0.29205161, 0.01112689, 0.51060286],
       [0.40329647, 0.22689038, 0.49360349]])

In [8]:
# "randint" is used to generate random integers between upper and lower bounds
z = np.random.randint(1,90)
z

35

In [9]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 10)
x

array([10, 81, 48, 75, 47,  6,  9, 79, 48, 25])

In [10]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# create a diagional of ones and zeros everywhere else
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Matrix of ones
i = np.ones((7,7))
i

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Array of zeros
zero = np.zeros(5)
zero


array([0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [14]:
x =int(input('Enter integer: '))


Enter integer: 20


In [15]:
y = np.random.randint(0, x, 10)
y

array([ 6, 10,  2,  4, 14, 14, 14,  0, 17, 19])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [16]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Add 2 numpy arrays together
sum=x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [20]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
exp = np.exp(y)
exp

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [22]:
X = np.array([5, 7, 20])
Y = np.array([9,15,4])
z = np.sqrt( X**2 + Y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [23]:
my_numpy = np.array([3, 5, 7, 2, 9, 10 , 20 ,50])
my_numpy

array([ 3,  5,  7,  2,  9, 10, 20, 50])

In [24]:
# Access specific index from the numpy array
my_numpy[2]

7

In [25]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy[0:-1]

array([ 3,  5,  7,  2,  9, 10, 20])

In [26]:
# Broadcasting, altering several values in a numpy array at once
my_numpy[0:4] = 7
my_numpy

array([ 7,  7,  7,  7,  9, 10, 20, 50])

In [27]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4,4))
matrix

array([[9, 7, 5, 1],
       [8, 9, 5, 6],
       [7, 8, 7, 2],
       [9, 2, 8, 4]])

In [28]:
# Get a row from a mtrix
matrix[0]

array([9, 7, 5, 1])

In [29]:
# Get one element
matrix[0][2]

5

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [30]:
X = np.array([
    [2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [31]:
X[4]=0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [32]:
mat = np.random.randint(1, 10,(5,5))
mat

array([[1, 4, 3, 6, 7],
       [1, 2, 8, 7, 8],
       [9, 9, 3, 4, 2],
       [6, 3, 8, 8, 8],
       [2, 6, 9, 6, 1]])

In [33]:
new_mat = mat[mat>7]
new_mat

array([8, 8, 9, 9, 8, 8, 8, 9])

In [34]:
# Obtain odd elements only
odd = mat[mat % 2 ==0]
odd

array([4, 6, 2, 8, 8, 4, 2, 6, 8, 8, 8, 2, 6, 6])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [35]:
X = np.array([
    [2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

In [36]:
X[X < 0]=0
X[X % 2 == 1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [37]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [2]:
import pandas as pd

In [39]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_df = pd.DataFrame({'Bank Client ID':[111,222,333,444],
                       'Bank Client Name':['Astrid', 'Gloria', 'Phil', 'Luke'],
                       'Net worth [$]': [2000,2800,3000,10000],
                       'Years with Bank': [1,4,6,8]})
bank_df

Bank Client ID Bank Client Name  Net worth [$]  Years with Bank
0             111           Astrid           2000                1
1             222           Gloria           2800                4
2             333             Phil           3000                6
3             444             Luke          10000                8

In [40]:
# Let's obtain the data type 
type(bank_df)

pandas.core.frame.DataFrame

In [41]:
# you can only view the first couple of rows using .head()
bank_df.head(2)

Bank Client ID Bank Client Name  Net worth [$]  Years with Bank
0             111           Astrid           2000                1
1             222           Gloria           2800                4

In [42]:
# you can only view the last couple of rows using .tail()
bank_df.tail(2)

Bank Client ID Bank Client Name  Net worth [$]  Years with Bank
2             333             Phil           3000                6
3             444             Luke          10000                8

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [43]:
portfolio = pd.DataFrame({'Stocks': ['AAPL','AMZN','MSFT'],
                         'Num of shares': [2,5,3],
                         'Price per share [$]': [34,67.2,88]})
portfolio

Stocks  Num of shares  Price per share [$]
0   AAPL              2                 34.0
1   AMZN              5                 67.2
2   MSFT              3                 88.0

In [44]:
stock_value = portfolio['Num of shares'] * portfolio['Price per share [$]']
stock_value.sum()

668.0

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [45]:
pip install html5lib

Note: you may need to restart the kernel to use updated packages.


tensorboard 2.1.1 has requirement setuptools>=41.0.0, but you'll have setuptools 39.0.1 which is incompatible.
google-auth 1.12.0 has requirement setuptools>=40.3.0, but you'll have setuptools 39.0.1 which is incompatible.
You are using pip version 10.0.1, however version 22.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [46]:
pip install lxml


tensorboard 2.1.1 has requirement setuptools>=41.0.0, but you'll have setuptools 39.0.1 which is incompatible.
google-auth 1.12.0 has requirement setuptools>=40.3.0, but you'll have setuptools 39.0.1 which is incompatible.
You are using pip version 10.0.1, however version 22.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [78]:
# Pandas is used to read a csv file and store data in a DataFrame
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [79]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [82]:
# Read tabular data using read_html
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

# 

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [83]:
usa_retirement_data_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
usa_retirement_data_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [88]:
# Let's define a dataframe as follows:
bank_df = pd.DataFrame({'Bank Client ID':[111,222,333,444],
                       'Bank Client Name':['Astrid', 'Gloria', 'Phil', 'Luke'],
                       'Net worth [$]': [2000,2800,8000,10000],
                       'Years with Bank': [1,4,6,8]})
bank_df

Bank Client ID Bank Client Name  Net worth [$]  Years with Bank
0             111           Astrid           2000                1
1             222           Gloria           2800                4
2             333             Phil           8000                6
3             444             Luke          10000                8

In [85]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_df[bank_df['Years with Bank']>=5]
df_loyal

Bank Client ID Bank Client Name  Net worth [$]  Years with Bank
2             333             Phil           3000                6
3             444             Luke          10000                8

In [86]:
# Delete a column from a DataFrame
del bank_df['Bank Client ID']
bank_df

Bank Client Name  Net worth [$]  Years with Bank
0           Astrid           2000                1
1           Gloria           2800                4
2             Phil           3000                6
3             Luke          10000                8

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [94]:
df_net_worth = bank_df[ bank_df['Net worth [$]']>=5000]
df_net_worth

Bank Client ID Bank Client Name  Net worth [$]  Years with Bank
2             333             Phil           8000                6
3             444             Luke          10000                8

In [95]:
df_net_worth['Net worth [$]'].sum()

18000

# TASK #9: PANDAS WITH FUNCTIONS

In [52]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [96]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 

def networth_update(balance):
    return balance * 1.2


In [99]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [101]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [103]:
def triple_stock(stock_val):
    return stock_val * 3 + 200

In [105]:
results = bank_client_df['Net worth [$]'].apply(triple_stock)
results.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [55]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [107]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by='Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [113]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [110]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by='Years with bank', inplace=True)

In [111]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [60]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [118]:
df1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2', 'A3'],
                   'B' : ['B0', 'B1', 'B2', 'B3'],
                   'C' : ['C0', 'C1', 'C2', 'C3'],
                    'D' : ['D0', 'D1', 'D2', 'D3']
                   }, index = [0,1,2,3,])

In [119]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [117]:
df2 = pd.DataFrame({'A' : ['A4', 'A5', 'A6', 'A7'],
                   'B' : ['B4', 'B5', 'B6', 'B7'],
                   'C' : ['C4', 'C5', 'C6', 'C7'],
                    'D' : ['D4', 'D5', 'D6', 'D7']
                   }, index = [4,5,6,7,])

In [120]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [122]:
df3 = pd.DataFrame({'A' : ['A8', 'A9', 'A10', 'A11'],
                   'B' : ['B8', 'B9', 'B10', 'B11'],
                   'C' : ['C8', 'C9', 'C10', 'C11'],
                    'D' : ['D8', 'D9', 'D10', 'D11']
                   }, index = [8,9,10,11])

In [123]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [124]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [6]:
raw = {'Bank Client ID': ['1','2','3','4','5'],
      'First Name': ['Alex', 'Gloria', 'Luke', 'Jay', 'Claire'],
      'Last Name': ['Fernandes', 'Connor', 'Dermott', 'Black', 'Tucker']}

In [7]:
Bank_df_1 = pd.DataFrame(raw, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1

Bank Client ID First Name  Last Name
0              1       Alex  Fernandes
1              2     Gloria     Connor
2              3       Luke    Dermott
3              4        Jay      Black
4              5     Claire     Tucker

In [8]:
raw_2 = {'Bank Client ID': ['6','7','8','9','10'],
      'First Name': ['Steve', 'Manny', 'Haley', 'Amy', 'Dina'],
      'Last Name': ['Garett', 'Elias', 'Ryan', 'Eghan', 'Scott']}

In [10]:
Bank_df_2 = pd.DataFrame(raw_2, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

Bank Client ID First Name Last Name
0              6      Steve    Garett
1              7      Manny     Elias
2              8      Haley      Ryan
3              9        Amy     Eghan
4             10       Dina     Scott

In [22]:
raw_3 = {'Bank Client ID': ['1','2','3','4','5','6','7','8','9','10'],
        'Annual Salary': [25000,30000,34000,89000,23000,50000,70000,10000,29000,34000]}
Bank_df_salary = pd.DataFrame(raw_3, columns = ['Bank Client ID', 'Annual Salary'])
Bank_df_salary

Bank Client ID  Annual Salary
0              1          25000
1              2          30000
2              3          34000
3              4          89000
4              5          23000
5              6          50000
6              7          70000
7              8          10000
8              9          29000
9             10          34000

In [23]:
Bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
Bank_df_all

Bank Client ID First Name  Last Name
0              1       Alex  Fernandes
1              2     Gloria     Connor
2              3       Luke    Dermott
3              4        Jay      Black
4              5     Claire     Tucker
0              6      Steve     Garett
1              7      Manny      Elias
2              8      Haley       Ryan
3              9        Amy      Eghan
4             10       Dina      Scott

In [24]:
Bank_all = pd.merge(Bank_df_all, Bank_df_salary, on = 'Bank Client ID' )
Bank_all

Bank Client ID First Name  Last Name  Annual Salary
0              1       Alex  Fernandes          25000
1              2     Gloria     Connor          30000
2              3       Luke    Dermott          34000
3              4        Jay      Black          89000
4              5     Claire     Tucker          23000
5              6      Steve     Garett          50000
6              7      Manny      Elias          70000
7              8      Haley       Ryan          10000
8              9        Amy      Eghan          29000
9             10       Dina      Scott          34000

In [25]:
new_client = {'Bank Client ID': ['11'],
             'First Name': ['Astrid'],
             'Last Name': ['Ferreira'],
             'Annual Salary': [50000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary
0             11     Astrid  Ferreira          50000

In [26]:
new_df = pd.concat([Bank_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary
0              1       Alex  Fernandes          25000
1              2     Gloria     Connor          30000
2              3       Luke    Dermott          34000
3              4        Jay      Black          89000
4              5     Claire     Tucker          23000
5              6      Steve     Garett          50000
6              7      Manny      Elias          70000
7              8      Haley       Ryan          10000
8              9        Amy      Eghan          29000
9             10       Dina      Scott          34000
0             11     Astrid   Ferreira          50000

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [61]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

array([[[3, 7, 9, 3],
        [4, 3, 2, 2]]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [62]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

Please enter a positive integer value: 4


array([1, 3, 2, 3, 1, 1, 1, 2, 2, 1])

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [63]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [64]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [65]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [66]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [67]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [68]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660


MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [69]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

[                                        Year of birth  \
 0                                      1937 and prior   
 1                                                1938   
 2                                                1939   
 3                                                1940   
 4                                                1941   
 5                                                1942   
 6                                             1943-54   
 7                                                1955   
 8                                                1956   
 9                                                1957   
 10                                               1958   
 11                                               1959   
 12                                     1960 and later   
 13  Notes: 1. Persons born on January 1 of any yea...   
 
                                                   Age  
 0                                                  65  
 1            

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [70]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

Bank client ID Bank Client Name  Net worth [$]  Years with bank
1             222            Steve          29000                4
2             333            Mitch          10000                9

In [71]:
df_high_networth['Net worth [$]'].sum()

39000

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [72]:
def networth_update(balance):
    return balance * 3 + 200 

In [73]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [74]:
results.sum()

134300

PROJECT SOLUTION:

In [75]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

In [76]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [77]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000